### ISSUE TITLE
terminate called after throwing an instance of 'std::runtime_error'   what():  Cannot open CHGAR!

### ISSUE THREAD

**Issue by filipejunqueira** [ifilot/edp#11]
Hi, 

I'm trying to run this on H2O on C60. I'm getting the following error when running:

 $ edp -i CHGAR -v 1,0,0 -w 0,0,1 -p 5,3.60358,3.8327 -s 100 -o test.png
--------------------------------------------------------------
Executing EDP v.1.9.0
Author: Ivo Filot <i.a.w.filot@tue.nl>
--------------------------------------------------------------
CHGAR is identified as a CHGCAR/PARCHG file. This means that we perform a volume correction on it as described in the link below:
https://cms.mpi.univie.ac.at/vasp/vasp/CHGCAR_file.html#file-chgcar.

terminate called after throwing an instance of 'std::runtime_error'
  what():  Cannot open CHGAR!
Aborted (core dumped)

Any idea what this could be? 
Thanks,

Filipe

PS: https://cms.mpi.univie.ac.at/vasp/vasp/CHGCAR_file.html#file-chgcar. does not seems to exist anymore.

**Comment by ifilot** [comment]
I am guessing you made a simple typo by typing `CHGAR` instead of `CHGCAR` (note the missing 'C').  The error message is hopefully clear about this: it says it cannot open the file. If you are sure the file exists, other options is to check whether you have read permission for the file.
