### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by mlorke** [ifilot/edp#8]
when trying to compile on a new system I get the following error
---------------------------------------------------------------------------------------------
-- Found the following Boost libraries:
--   regex
--   iostreams
--   filesystem
--   system
-- Checking for module 'tclap'
--   Found tclap, version 1.2.1
-- Checking for module 'cairo'
--   Found cairo, version 1.14.6
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mlorke/bin/edp-develop/build
mlorke@aguser-virtuell1:~/bin/edp-develop/build$ make -j5
Scanning dependencies of target edp
[ 12%] Building CXX object CMakeFiles/edp.dir/scalar_field.cpp.o
[ 25%] Building CXX object CMakeFiles/edp.dir/raycaster.cpp.o
[ 37%] Building CXX object CMakeFiles/edp.dir/quadrature.cpp.o
[ 50%] Building CXX object CMakeFiles/edp.dir/plotter.cpp.o
[ 62%] Building CXX object CMakeFiles/edp.dir/edp.cpp.o
[ 75%] Building CXX object CMakeFiles/edp.dir/planeprojector.cpp.o
[ 87%] Building CXX object CMakeFiles/edp.dir/periodic_table.cpp.o
/home/mlorke/bin/edp-develop/src/planeprojector.cpp: In member function ‘float PlaneProjector::calculate_scaled_value_log(float)’:
/home/mlorke/bin/edp-develop/src/planeprojector.cpp:570:82: error: no matching function for call to ‘max(double, float&)’
     const float logval = std::min(std::max(log10(std::fabs(input)), this->log_min), this->log_max);
                                                                                  ^
In file included from /usr/include/c++/5/algorithm:61:0,
                 from /home/mlorke/bin/edp-develop/src/planeprojector.h:24,
                 from /home/mlorke/bin/edp-develop/src/planeprojector.cpp:21:
/usr/include/c++/5/bits/stl_algobase.h:219:5: note: candidate: template<class _Tp> constexpr const _Tp& std::max(const _Tp&, const _Tp&)
     max(const _Tp& __a, const _Tp& __b)
     ^
/usr/include/c++/5/bits/stl_algobase.h:219:5: note:   template argument deduction/substitution failed:
/home/mlorke/bin/edp-develop/src/planeprojector.cpp:570:82: note:   deduced conflicting types for parameter ‘const _Tp’ (‘double’ and ‘float’)
     const float logval = std::min(std::max(log10(std::fabs(input)), this->log_min), this->log_max);
                                                                                  ^
In file included from /usr/include/c++/5/algorithm:61:0,
                 from /home/mlorke/bin/edp-develop/src/planeprojector.h:24,
                 from /home/mlorke/bin/edp-develop/src/planeprojector.cpp:21:
/usr/include/c++/5/bits/stl_algobase.h:265:5: note: candidate: template<class _Tp, class _Compare> constexpr const _Tp& std::max(const _Tp&, const _Tp&, _Compare)
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
     ^
/usr/include/c++/5/bits/stl_algobase.h:265:5: note:   template argument deduction/substitution failed:
/home/mlorke/bin/edp-develop/src/planeprojector.cpp:570:82: note:   deduced conflicting types for parameter ‘const _Tp’ (‘double’ and ‘float’)
     const float logval = std::min(std::max(log10(std::fabs(input)), this->log_min), this->log_max);
                                                                                  ^
In file included from /usr/include/c++/5/algorithm:62:0,
                 from /home/mlorke/bin/edp-develop/src/planeprojector.h:24,
                 from /home/mlorke/bin/edp-develop/src/planeprojector.cpp:21:
/usr/include/c++/5/bits/stl_algo.h:3457:5: note: candidate: template<class _Tp> constexpr _Tp std::max(std::initializer_list<_Tp>)
     max(initializer_list<_Tp> __l)
     ^
/usr/include/c++/5/bits/stl_algo.h:3457:5: note:   template argument deduction/substitution failed:
/home/mlorke/bin/edp-develop/src/planeprojector.cpp:570:82: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘double’
     const float logval = std::min(std::max(log10(std::fabs(input)), this->log_min), this->log_max);
                                                                                  ^
In file included from /usr/include/c++/5/algorithm:62:0,
                 from /home/mlorke/bin/edp-develop/src/planeprojector.h:24,
                 from /home/mlorke/bin/edp-develop/src/planeprojector.cpp:21:
/usr/include/c++/5/bits/stl_algo.h:3463:5: note: candidate: template<class _Tp, class _Compare> constexpr _Tp std::max(std::initializer_list<_Tp>, _Compare)
     max(initializer_list<_Tp> __l, _Compare __comp)
     ^
/usr/include/c++/5/bits/stl_algo.h:3463:5: note:   template argument deduction/substitution failed:
/home/mlorke/bin/edp-develop/src/planeprojector.cpp:570:82: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘double’
     const float logval = std::min(std::max(log10(std::fabs(input)), this->log_min), this->log_max);
                                                                                  ^
CMakeFiles/edp.dir/build.make:182: recipe for target 'CMakeFiles/edp.dir/planeprojector.cpp.o' failed
make[2]: *** [CMakeFiles/edp.dir/planeprojector.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/edp.dir/all' failed
make[1]: *** [CMakeFiles/edp.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
---------------------------------------------------------------------------------------------

as far as I can tell all dependencies are fulfilled, what could be the problem here?

**Comment by ifilot** [comment]
Apparently it trips on the std::min/std::max functions. The reason is that the compiler does not want to use the function when the float point types differ (which is logical). 

Can you provide some more detail? What is your version of gcc? If I can reproduce, it might be able to fix it for you.

A solution is to manually set the floating points by adding (float) or (double) in front of the variables.

**Comment by mlorke** [comment]
my gcc version is 
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by ifilot** [comment]
Thanks for the information. I have made some modifications in the source code. Can you switch to the `bugfix` branch and see if the compilation is now working for you? You might need to rerun `cmake ../src`.

**Comment by mlorke** [comment]
now I get 

Scanning dependencies of target edp
[ 12%] Building CXX object CMakeFiles/edp.dir/raycaster.cpp.o
[ 25%] Building CXX object CMakeFiles/edp.dir/quadrature.cpp.o
[ 62%] Building CXX object CMakeFiles/edp.dir/scalar_field.cpp.o
[ 37%] Building CXX object CMakeFiles/edp.dir/edp.cpp.o
[ 62%] Building CXX object CMakeFiles/edp.dir/plotter.cpp.o
[ 75%] Building CXX object CMakeFiles/edp.dir/planeprojector.cpp.o
[ 87%] Building CXX object CMakeFiles/edp.dir/periodic_table.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
CMakeFiles/edp.dir/build.make:86: recipe for target 'CMakeFiles/edp.dir/scalar_field.cpp.o' failed
make[2]: *** [CMakeFiles/edp.dir/scalar_field.cpp.o] Error 4
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/edp.dir/all' failed
make[1]: *** [CMakeFiles/edp.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
mlorke@aguser-virtuell1:~/bin/edp-bugfix/build$ 

 I redownloaded the "bugfix" branch to start essentially "from scratch", reran cmake

**Comment by ifilot** [comment]
Can you completely remove all source code and the build directory and rebuild from scratch? What build command you use?

**Comment by ifilot** [comment]
For your information: this is what I do to compile:

```
ivo@debian:~/edp/build$ mak^C
ivo@debian:~/edp/build$ cd ..
ivo@debian:~/edp$ rm -rf build/
ivo@debian:~/edp$ mkdir build
ivo@debian:~/edp$ cd build/
ivo@debian:~/edp/build$ cmake ../src
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Setting build type to 'Release' as none was specified.
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.28")
-- Looking for GLM
-- Found GLM include directory: /usr/include
-- Boost version: 1.55.0
-- Found the following Boost libraries:
--   regex
--   iostreams
--   filesystem
--   system
-- checking for module 'tclap'
--   found tclap, version 1.2.1
-- checking for module 'cairo'
--   found cairo, version 1.14.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ivo/edp/build
ivo@debian:~/edp/build$ make
Scanning dependencies of target edp
[ 14%] Building CXX object CMakeFiles/edp.dir/periodic_table.cpp.o
[ 28%] Building CXX object CMakeFiles/edp.dir/edp.cpp.o
[ 42%] Building CXX object CMakeFiles/edp.dir/planeprojector.cpp.o
[ 57%] Building CXX object CMakeFiles/edp.dir/raycaster.cpp.o
[ 71%] Building CXX object CMakeFiles/edp.dir/quadrature.cpp.o
[ 85%] Building CXX object CMakeFiles/edp.dir/scalar_field.cpp.o
[100%] Building CXX object CMakeFiles/edp.dir/plotter.cpp.o
Linking CXX executable edp
[100%] Built target edp
ivo@debian:~/edp/build$
```

**Comment by mlorke** [comment]
now it works,
I tried to use "make -j5" as per the README file, and that killed it. a simple "make" did run through smoothly

**Comment by ifilot** [comment]
Excellent! I will merge this bugfix then into the master branch. Thank you for your feedback!
